[package]
name = "workload"
version = "0.1.0"
authors = ["David McKay <david@rawkode.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
actix-web = "3.3.2"
actix-files = "0.5.0"
postgres = "0.19.0"
